#!/usr/bin/env bash

@()
{
	(set -x ; "$@")
	echo
}

echo
echo '/-------------------\'
echo "| kapnoc's dotfiles |"
echo '\-------------------/'
echo

PKG="xbps-install"

@ sudo $PKG -S

################
# needed tools #
################
@ sudo $PKG curl wget git

source sh/vim.sh
install_vim

source sh/zsh.sh
install_zsh


################
# urxvt config #
################
@ sudo $PKG rxvt-unicode libcaca ranger asciiquarium asciinema
@ cp files/.urxvt ~/ -r
@ cp files/.Xdefaults ~/
@ cp files/ranger ~/.config -r


# add Numix
# add blih

source sh/herbstluftwm.sh
install_herbstluft

#########
# ~/bin #
#########
cp -r files/bin ~/
git clone https://github.com/Bassintag551/EpitechCodeAnalyser ~/bin/EpitechCodeAnalyser
ln -s ~/bin/EpitechCodeAnalyser/CodeAnalyser.py ~/bin/moumou
git clone https://github.com/kapnoc/todo-sh ~/bin/todo-sh
ln -s ~/bin/todo-sh/todo ~/bin/todo


echo "flat-volumes = no" | sudo tee -a /etc/pulse/daemon.conf

####################
# various packages #
####################
@ sudo $PKG nethack
@ sudo $PKG gcc nasm make ncurses-devel
@ sudo $PKG tree
@ sudo $PKG neofetch
@ sudo $PKG fortune-mod{,-void}
@ sudo $PKG i3lock ImageMagick scrot ; mkdir -p ~/tmp

echo
echo "DONE :)"
echo
